Add a check to ensure g++ and gcov versions are matching

diff --git a/linux-x86/Dockerfile b/linux-x86/Dockerfile
--- a/linux-x86/Dockerfile
+++ b/linux-x86/Dockerfile
@@ -23,12 +23,22 @@ RUN apt-get update -qq && apt-get install -y -qq \
     xz-utils \
 && rm -rf /var/lib/apt/lists/*
 
-
 # Setup tools versions
 RUN update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-15 15
 RUN update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-15 15
 RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12
 RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12
+
+# Check for possible mismatch between g++ and gcov versions
+RUN GCC_VERSION=$(g++ -dumpfullversion) \
+&& GCOV_VERSION=$( gcov --version | head -n 1 | grep -oP "\b\d{1,2}\.\d{1,2}\.\d{1,2}\b" | head -n 1) \
+&& if [ "$GCC_VERSION" = "$GCOV_VERSION" ]; \
+    then \
+        echo "Versions match: gcov $GCOV_VERSION and g++ $GCC_VERSION"; \
+    else \
+        echo "Error: g++ version is $GCC_VERSION but gcov version is $GCOV_VERSION"; \
+        exit 1; \
+    fi
 
 # Install cmake-format
 RUN pip3 install cmake-format
